db:
  image: postgres:9.4

redis:
  image: redis:3

web:
  image: crystalnix/omaha-server:stable
  privileged: true
  ports:
    - "9090:80"
  environment:
    DB_HOST: db
    DB_PORT: 5432
    DB_USER: postgres
    DB_NAME: postgres
    DB_PASSWORD: ''
    HOST_NAME: '*'
    SECRET_KEY: 'SECRET_KEY'
    DJANGO_SETTINGS_MODULE: 'omaha_server.settings'
    AWS_ACCESS_KEY_ID: 'AWS_ACCESS_KEY_ID'
    AWS_SECRET_ACCESS_KEY: 'AWS_SECRET_ACCESS_KEY'
    AWS_STORAGE_BUCKET_NAME: 'AWS_STORAGE_BUCKET_NAME'
    REDIS_HOST: redis
    REDIS_PORT: 6379
    OMAHA_SERVER_PRIVATE: 'True'
    AWS_ROLE: 'omaha-private'
    DB_PUBLIC_USER: 'omaha_public'
    DB_PUBLIC_PASSWORD: 'omaha_public_password'
    UWSGI_PROCESSES: 10
    UWSGI_THREADS: 8
